export const ORDER_LIST = "ORDER_LIST";
export const SET_FILTERS = "SET_FILTERS";
export const TOGGLE_FILTERS = "TOGGLE_FILTERS";
export const SHOW_DROPDOWN = "SHOW_DROPDOWN";
export const SET_CLEAR_ALL_INPUT = "SET_CLEAR_ALL_INPUT";
export const SET_CLEAR_ACTIVE_INPUT = "SET_CLEAR_ACTIVE_INPUT";
